openapi: 3.0.0
info:
  version: 0.0.2
  title: ICU
  description: Satellite image query service
  termsOfService: https://www.polestarglobal.com/
  contact:
    name: Pole Star Space Applications ICU Development Team
    url: https://www.polestarglobal.com/contact-us/
    email: support@polestarglobal.com
  license:
    name: Proprietary License
    url: https://www.polestarglobal.com/
paths:
  "/health":
    get:
      operationId: app.views.health
      description: Health check for service
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  "/image":
    post:
      operationId: app.views.image
      description: Fetch an image from space
      requestBody:
        description: location to image
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
                zoom:
                  type: number
                provider:
                  type: string
                  enum:
                    - google
                    - arcgis
                  default: google
      responses:
        "200":
          description: Ship disambiguated
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: Error Message
servers:
  - url: http://0.0.0.0:5000/api/v1/
components:
  responses:
    BadRequest:
      description: Bad Request error
