version: '3.7'

services:
  icu-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - 178847878690.dkr.ecr.us-east-1.amazonaws.com/disam:testing
        - 205287409906.dkr.ecr.us-east-1.amazonaws.com/disam:latest
        - 205287409906.dkr.ecr.us-east-1.amazonaws.com/disam:testing
        - disam:testing
        - disam:latest
        - disam:latest-test
    volumes:
      - ./:/opt/icu/
    healthcheck:
      test: nc -z localhost:5000
      interval: 30s
      timeout: 30s
      retries: 15

